Add new redirect application to README.md
fecgov/FEC pull request #10522
Opened 2020-11-17 00:09 UTC by lbeaufort

- Add new redirect application to README.md

2020-11-17 14:15 UTC, jason-upchurch approved these changes
Thank you @lbeaufort 👍

2020-11-18 00:55 UTC, PaulClark2 requested changes

2020-11-18 00:55 UTC, PaulClark2 commented on README.md
FEC.gov began as a collaboration between [18F](https://18f.gsa.gov) and the [FEC](https://www.fec.gov) in an effort to make campaign finance information more accessible (and understandable) to all users. The FEC continues to improve the site and add functionality.

2020-11-18 00:57 UTC, PaulClark2 commented on README.md
FEC.gov began as a collaboration between [18F](https://18f.gsa.gov) and the [FEC](https://www.fec.gov) in an effort to make campaign finance information more accessible (and understandable) to all users. The FEC continues to improve the site and add functionality.

2020-11-18 01:03 UTC, PaulClark2 commented on README.md
“The current version of” could be better. We should not call the site “the new” FEC.gov.

2020-11-19 23:18 UTC, lbeaufort commented on README.md
@PaulClark2 agreed! What do you think about: 

>FEC.gov began as a collaboration between 18F and the FEC to make campaign finance information more accessible (and understandable) to all users. The FEC continues to improve the site and add functionality.

2020-11-20 02:03 UTC, PaulClark2 commented on README.md
@lbeaufort this looks good to me.

2020-11-20 14:49 UTC, PaulClark2 approved these changes
You're suggested edits look good to me.

2020-11-24 14:58 UTC, merged